//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationRuRu.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationRuRu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cамодиагностика.
        /// </summary>
        public static string Program_0 {
            get {
                return ResourceManager.GetString("Program_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тестирование всех узлов и калибровка. Запускать после установки, без белья.
        /// </summary>
        public static string Program_0_Comment {
            get {
                return ResourceManager.GetString("Program_0_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хлопок 90° с предв.стиркой.
        /// </summary>
        public static string Program_1 {
            get {
                return ResourceManager.GetString("Program_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очень сильно загрязненное белое белье (простыни, скатерти, и т.д.).
        /// </summary>
        public static string Program_1_Comment {
            get {
                return ResourceManager.GetString("Program_1_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шерсть.
        /// </summary>
        public static string Program_10 {
            get {
                return ResourceManager.GetString("Program_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шелк.
        /// </summary>
        public static string Program_11 {
            get {
                return ResourceManager.GetString("Program_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полоскание.
        /// </summary>
        public static string Program_12 {
            get {
                return ResourceManager.GetString("Program_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деликатное полоскание.
        /// </summary>
        public static string Program_13 {
            get {
                return ResourceManager.GetString("Program_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отжим.
        /// </summary>
        public static string Program_14 {
            get {
                return ResourceManager.GetString("Program_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деликатный отжим.
        /// </summary>
        public static string Program_15 {
            get {
                return ResourceManager.GetString("Program_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слив.
        /// </summary>
        public static string Program_16 {
            get {
                return ResourceManager.GetString("Program_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слив шлангов.
        /// </summary>
        public static string Program_17 {
            get {
                return ResourceManager.GetString("Program_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Водонагреватель.
        /// </summary>
        public static string Program_18 {
            get {
                return ResourceManager.GetString("Program_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Притирка щеток.
        /// </summary>
        public static string Program_19 {
            get {
                return ResourceManager.GetString("Program_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хлопок 90°.
        /// </summary>
        public static string Program_2 {
            get {
                return ResourceManager.GetString("Program_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хлопок 60°.
        /// </summary>
        public static string Program_3 {
            get {
                return ResourceManager.GetString("Program_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хлопок 40°.
        /// </summary>
        public static string Program_4 {
            get {
                return ResourceManager.GetString("Program_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хлопок 30°.
        /// </summary>
        public static string Program_5 {
            get {
                return ResourceManager.GetString("Program_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синтетика 60°.
        /// </summary>
        public static string Program_6 {
            get {
                return ResourceManager.GetString("Program_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синтетика 50°.
        /// </summary>
        public static string Program_7 {
            get {
                return ResourceManager.GetString("Program_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синтетика 40°.
        /// </summary>
        public static string Program_8 {
            get {
                return ResourceManager.GetString("Program_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синтетика 30°.
        /// </summary>
        public static string Program_9 {
            get {
                return ResourceManager.GetString("Program_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stage_1.
        /// </summary>
        public static string Stage_1 {
            get {
                return ResourceManager.GetString("Stage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stage_2.
        /// </summary>
        public static string Stage_2 {
            get {
                return ResourceManager.GetString("Stage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stage_3.
        /// </summary>
        public static string Stage_3 {
            get {
                return ResourceManager.GetString("Stage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stage_4.
        /// </summary>
        public static string Stage_4 {
            get {
                return ResourceManager.GetString("Stage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} Connected.
        /// </summary>
        public static string Status_Connected {
            get {
                return ResourceManager.GetString("Status_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение....
        /// </summary>
        public static string Status_Connecting {
            get {
                return ResourceManager.GetString("Status_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection break.
        /// </summary>
        public static string Status_ConnectionBreak {
            get {
                return ResourceManager.GetString("Status_ConnectionBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено.
        /// </summary>
        public static string Status_NotFound {
            get {
                return ResourceManager.GetString("Status_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: {1}.
        /// </summary>
        public static string Status_Washing {
            get {
                return ResourceManager.GetString("Status_Washing", resourceCulture);
            }
        }
    }
}
