//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenWasherClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenWasherClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap options {
            get {
                object obj = ResourceManager.GetObject("options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Self-diagnostics.
        /// </summary>
        internal static string Program_0 {
            get {
                return ResourceManager.GetString("Program_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All component self testing. Run without laundry after installation or flashing.
        /// </summary>
        internal static string Program_0_Comment {
            get {
                return ResourceManager.GetString("Program_0_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сotton 90° with prewashing.
        /// </summary>
        internal static string Program_1 {
            get {
                return ResourceManager.GetString("Program_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extremely soiled whites (sheets, tablecloths, etc.).
        /// </summary>
        internal static string Program_1_Comment {
            get {
                return ResourceManager.GetString("Program_1_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wool.
        /// </summary>
        internal static string Program_10 {
            get {
                return ResourceManager.GetString("Program_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_10_Comment {
            get {
                return ResourceManager.GetString("Program_10_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silk.
        /// </summary>
        internal static string Program_11 {
            get {
                return ResourceManager.GetString("Program_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_11_Comment {
            get {
                return ResourceManager.GetString("Program_11_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rinse.
        /// </summary>
        internal static string Program_12 {
            get {
                return ResourceManager.GetString("Program_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_12_Comment {
            get {
                return ResourceManager.GetString("Program_12_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delicate rinse.
        /// </summary>
        internal static string Program_13 {
            get {
                return ResourceManager.GetString("Program_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_13_Comment {
            get {
                return ResourceManager.GetString("Program_13_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spin.
        /// </summary>
        internal static string Program_14 {
            get {
                return ResourceManager.GetString("Program_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_14_Comment {
            get {
                return ResourceManager.GetString("Program_14_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delicate spin.
        /// </summary>
        internal static string Program_15 {
            get {
                return ResourceManager.GetString("Program_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_15_Comment {
            get {
                return ResourceManager.GetString("Program_15_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drain.
        /// </summary>
        internal static string Program_16 {
            get {
                return ResourceManager.GetString("Program_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_16_Comment {
            get {
                return ResourceManager.GetString("Program_16_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drain pipes .
        /// </summary>
        internal static string Program_17 {
            get {
                return ResourceManager.GetString("Program_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_17_Comment {
            get {
                return ResourceManager.GetString("Program_17_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water heater.
        /// </summary>
        internal static string Program_18 {
            get {
                return ResourceManager.GetString("Program_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_18_Comment {
            get {
                return ResourceManager.GetString("Program_18_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grinding brushes.
        /// </summary>
        internal static string Program_19 {
            get {
                return ResourceManager.GetString("Program_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_19_Comment {
            get {
                return ResourceManager.GetString("Program_19_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сotton 90°.
        /// </summary>
        internal static string Program_2 {
            get {
                return ResourceManager.GetString("Program_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extremely soiled whites (sheets, tablecloths, etc.).
        /// </summary>
        internal static string Program_2_Comment {
            get {
                return ResourceManager.GetString("Program_2_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сotton 60°.
        /// </summary>
        internal static string Program_3 {
            get {
                return ResourceManager.GetString("Program_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heavily soiled whites and fast colours.
        /// </summary>
        internal static string Program_3_Comment {
            get {
                return ResourceManager.GetString("Program_3_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сotton 40°.
        /// </summary>
        internal static string Program_4 {
            get {
                return ResourceManager.GetString("Program_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slightly soiled whites and shedding colours.
        /// </summary>
        internal static string Program_4_Comment {
            get {
                return ResourceManager.GetString("Program_4_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сotton 30°.
        /// </summary>
        internal static string Program_5 {
            get {
                return ResourceManager.GetString("Program_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slightly soiled shedding colours.
        /// </summary>
        internal static string Program_5_Comment {
            get {
                return ResourceManager.GetString("Program_5_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synthetics 60°.
        /// </summary>
        internal static string Program_6 {
            get {
                return ResourceManager.GetString("Program_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_6_Comment {
            get {
                return ResourceManager.GetString("Program_6_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synthetics 50°.
        /// </summary>
        internal static string Program_7 {
            get {
                return ResourceManager.GetString("Program_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_7_Comment {
            get {
                return ResourceManager.GetString("Program_7_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synthetics 40°.
        /// </summary>
        internal static string Program_8 {
            get {
                return ResourceManager.GetString("Program_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_8_Comment {
            get {
                return ResourceManager.GetString("Program_8_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synthetics 30°.
        /// </summary>
        internal static string Program_9 {
            get {
                return ResourceManager.GetString("Program_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Program_9_Comment {
            get {
                return ResourceManager.GetString("Program_9_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spiral {
            get {
                object obj = ResourceManager.GetObject("spiral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        internal static string Stage_0 {
            get {
                return ResourceManager.GetString("Stage_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closing door.
        /// </summary>
        internal static string Stage_1 {
            get {
                return ResourceManager.GetString("Stage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocking door.
        /// </summary>
        internal static string Stage_2 {
            get {
                return ResourceManager.GetString("Stage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rinsing.
        /// </summary>
        internal static string Stage_3 {
            get {
                return ResourceManager.GetString("Stage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spinning.
        /// </summary>
        internal static string Stage_4 {
            get {
                return ResourceManager.GetString("Stage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prewashing.
        /// </summary>
        internal static string Stage_5 {
            get {
                return ResourceManager.GetString("Stage_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Washing.
        /// </summary>
        internal static string Stage_6 {
            get {
                return ResourceManager.GetString("Stage_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw water.
        /// </summary>
        internal static string Stage_7 {
            get {
                return ResourceManager.GetString("Stage_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sink.
        /// </summary>
        internal static string Stage_8 {
            get {
                return ResourceManager.GetString("Stage_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Self-testing.
        /// </summary>
        internal static string Stage_9 {
            get {
                return ResourceManager.GetString("Stage_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} Connected.
        /// </summary>
        internal static string Status_Connected {
            get {
                return ResourceManager.GetString("Status_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection error: {0}.
        /// </summary>
        internal static string Status_ConnectFailed {
            get {
                return ResourceManager.GetString("Status_ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection break.
        /// </summary>
        internal static string Status_ConnectionBreak {
            get {
                return ResourceManager.GetString("Status_ConnectionBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Washer not found.
        /// </summary>
        internal static string Status_NotFound {
            get {
                return ResourceManager.GetString("Status_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: {1}.
        /// </summary>
        internal static string Status_Washing {
            get {
                return ResourceManager.GetString("Status_Washing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thermometer {
            get {
                object obj = ResourceManager.GetObject("thermometer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap washing_machine {
            get {
                object obj = ResourceManager.GetObject("washing_machine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
