//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization_RuRU.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization_RuRU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность стирки, мин..
        /// </summary>
        internal static string Label_Duration {
            get {
                return ResourceManager.GetString("Label_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество полосканий.
        /// </summary>
        internal static string Label_RinsingCycles {
            get {
                return ResourceManager.GetString("Label_RinsingCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость отжима, об./мин..
        /// </summary>
        internal static string Label_SpinningSpeed {
            get {
                return ResourceManager.GetString("Label_SpinningSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура, °C.
        /// </summary>
        internal static string Label_Temperature {
            get {
                return ResourceManager.GetString("Label_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость стирки, об./мин..
        /// </summary>
        internal static string Label_WashingSpeed {
            get {
                return ResourceManager.GetString("Label_WashingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень воды, %.
        /// </summary>
        internal static string Label_WaterLevel {
            get {
                return ResourceManager.GetString("Label_WaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самодиагностика.
        /// </summary>
        internal static string Program_0 {
            get {
                return ResourceManager.GetString("Program_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поочередный тест всех компонентов. Запускать без белья после установки или переподключения.
        /// </summary>
        internal static string Program_0_Comment {
            get {
                return ResourceManager.GetString("Program_0_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хлопок 90° с предв..
        /// </summary>
        internal static string Program_1 {
            get {
                return ResourceManager.GetString("Program_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень сильно загрязненное белое белье (простыни, скатерти, и т.д.).
        /// </summary>
        internal static string Program_1_Comment {
            get {
                return ResourceManager.GetString("Program_1_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шерсть.
        /// </summary>
        internal static string Program_10 {
            get {
                return ResourceManager.GetString("Program_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шерсть.
        /// </summary>
        internal static string Program_10_Comment {
            get {
                return ResourceManager.GetString("Program_10_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шелк.
        /// </summary>
        internal static string Program_11 {
            get {
                return ResourceManager.GetString("Program_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особо деликатные ткани и одежда (завеси, шелк, вискоза и пр.).
        /// </summary>
        internal static string Program_11_Comment {
            get {
                return ResourceManager.GetString("Program_11_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полоскание.
        /// </summary>
        internal static string Program_12 {
            get {
                return ResourceManager.GetString("Program_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полоскание.
        /// </summary>
        internal static string Program_12_Comment {
            get {
                return ResourceManager.GetString("Program_12_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деликатное полоскание.
        /// </summary>
        internal static string Program_13 {
            get {
                return ResourceManager.GetString("Program_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деликатное полоскание.
        /// </summary>
        internal static string Program_13_Comment {
            get {
                return ResourceManager.GetString("Program_13_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отжим.
        /// </summary>
        internal static string Program_14 {
            get {
                return ResourceManager.GetString("Program_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отжим.
        /// </summary>
        internal static string Program_14_Comment {
            get {
                return ResourceManager.GetString("Program_14_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деликатный отжим.
        /// </summary>
        internal static string Program_15 {
            get {
                return ResourceManager.GetString("Program_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деликатный отжим.
        /// </summary>
        internal static string Program_15_Comment {
            get {
                return ResourceManager.GetString("Program_15_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слив.
        /// </summary>
        internal static string Program_16 {
            get {
                return ResourceManager.GetString("Program_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слив.
        /// </summary>
        internal static string Program_16_Comment {
            get {
                return ResourceManager.GetString("Program_16_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слив магистрали.
        /// </summary>
        internal static string Program_17 {
            get {
                return ResourceManager.GetString("Program_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слив с открытыми клапанами.
        /// </summary>
        internal static string Program_17_Comment {
            get {
                return ResourceManager.GetString("Program_17_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водонагреватель.
        /// </summary>
        internal static string Program_18 {
            get {
                return ResourceManager.GetString("Program_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водонагреватель.
        /// </summary>
        internal static string Program_18_Comment {
            get {
                return ResourceManager.GetString("Program_18_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Притирка щеток.
        /// </summary>
        internal static string Program_19 {
            get {
                return ResourceManager.GetString("Program_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Притирка щеток.
        /// </summary>
        internal static string Program_19_Comment {
            get {
                return ResourceManager.GetString("Program_19_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хлопок 90°.
        /// </summary>
        internal static string Program_2 {
            get {
                return ResourceManager.GetString("Program_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень сильно загрязненное белое белье (простыни, скатерти, и т.д.).
        /// </summary>
        internal static string Program_2_Comment {
            get {
                return ResourceManager.GetString("Program_2_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хлопок 60°.
        /// </summary>
        internal static string Program_3 {
            get {
                return ResourceManager.GetString("Program_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сильно загрязненное белое и прочно окрашенное цветное белье.
        /// </summary>
        internal static string Program_3_Comment {
            get {
                return ResourceManager.GetString("Program_3_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хлопок 40°.
        /// </summary>
        internal static string Program_4 {
            get {
                return ResourceManager.GetString("Program_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слабо загрязненное белое и линяющее цветное белье (рубашки, майки, и т.д.).
        /// </summary>
        internal static string Program_4_Comment {
            get {
                return ResourceManager.GetString("Program_4_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хлопок 30°.
        /// </summary>
        internal static string Program_5 {
            get {
                return ResourceManager.GetString("Program_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слабо загрязненное линяющее цветное белье.
        /// </summary>
        internal static string Program_5_Comment {
            get {
                return ResourceManager.GetString("Program_5_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синтетика 60°.
        /// </summary>
        internal static string Program_6 {
            get {
                return ResourceManager.GetString("Program_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сильно загрязненная, прочно окрашенная цветная (детская одежда и пр.).
        /// </summary>
        internal static string Program_6_Comment {
            get {
                return ResourceManager.GetString("Program_6_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синтетика 50°.
        /// </summary>
        internal static string Program_7 {
            get {
                return ResourceManager.GetString("Program_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сильно загрязненная, прочно окрашенная цветная (детская одежда и пр.).
        /// </summary>
        internal static string Program_7_Comment {
            get {
                return ResourceManager.GetString("Program_7_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синтетика 40°.
        /// </summary>
        internal static string Program_8 {
            get {
                return ResourceManager.GetString("Program_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слабо загрязненная, деликатная цветная (любая одежда).
        /// </summary>
        internal static string Program_8_Comment {
            get {
                return ResourceManager.GetString("Program_8_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синтетика 30°.
        /// </summary>
        internal static string Program_9 {
            get {
                return ResourceManager.GetString("Program_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слабо загрязненная, деликатная цветная (любая одежда).
        /// </summary>
        internal static string Program_9_Comment {
            get {
                return ResourceManager.GetString("Program_9_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to стоп.
        /// </summary>
        internal static string Stage_0 {
            get {
                return ResourceManager.GetString("Stage_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to блокировка люка.
        /// </summary>
        internal static string Stage_1 {
            get {
                return ResourceManager.GetString("Stage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to разблокировка люка.
        /// </summary>
        internal static string Stage_2 {
            get {
                return ResourceManager.GetString("Stage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to полоскание.
        /// </summary>
        internal static string Stage_3 {
            get {
                return ResourceManager.GetString("Stage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отжим.
        /// </summary>
        internal static string Stage_4 {
            get {
                return ResourceManager.GetString("Stage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to предв.стирка.
        /// </summary>
        internal static string Stage_5 {
            get {
                return ResourceManager.GetString("Stage_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to стирка.
        /// </summary>
        internal static string Stage_6 {
            get {
                return ResourceManager.GetString("Stage_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to набор воды.
        /// </summary>
        internal static string Stage_7 {
            get {
                return ResourceManager.GetString("Stage_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to слив.
        /// </summary>
        internal static string Stage_8 {
            get {
                return ResourceManager.GetString("Stage_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to самотестирование.
        /// </summary>
        internal static string Stage_9 {
            get {
                return ResourceManager.GetString("Stage_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключено через {0}.
        /// </summary>
        internal static string Status_Connected {
            get {
                return ResourceManager.GetString("Status_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось подключиться.
        /// </summary>
        internal static string Status_ConnectFailed {
            get {
                return ResourceManager.GetString("Status_ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет связи.
        /// </summary>
        internal static string Status_ConnectionBreak {
            get {
                return ResourceManager.GetString("Status_ConnectionBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено.
        /// </summary>
        internal static string Status_NotFound {
            get {
                return ResourceManager.GetString("Status_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переподключение.
        /// </summary>
        internal static string Status_Reconnecting {
            get {
                return ResourceManager.GetString("Status_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Status_Washing {
            get {
                return ResourceManager.GetString("Status_Washing", resourceCulture);
            }
        }
    }
}
